config:
  warningsAsErrors: false

console-reports:
  active: true

output-reports:
  active: true

exceptions:
  SwallowedException:
    active: false
  ThrowsCount:
    active: true
    max: 3

style:
  ForbiddenComment:
    active: false
